import "~/styles/globals.css";

import { Nunito } from "next/font/google";
import { type Metadata } from "next";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${nunito.className}`}>
      <body className="mx-auto my-0 box-border max-w-screen-lg px-0 py-6">
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-slate-100 mx-auto my-0 box-border max-w-screen-lg px-0 py-6">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
