import "~/styles/globals.css";

import { Nunito } from "next/font/google";
import { type Metadata } from "next";

const nunito = Nunito({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${nunito.className}`}>
      <body>{children}</body>
    </html>
  );
}
